### PR TITLE
add llama3 variants

### LINKED ISSUE #4: Add new models - Llama 3 and Mixtral 8x22b
Full list now is:
```
    "llama3-8b-8192",
    "llama3-70b-8192",
    "llama2-70b-4096",
    "mixtral-8x7b-32768",
    "gemma-7b-it",
```
https://console.groq.com/docs/models

### PR DESCRIPTION
**Pull request by lexh**
closes #4

### CODE REVIEW

**Comment by simonw** [comment]
I manually tested this like so:
```bash
llm install https://github.com/lexh/llm-groq/archive/ba9d7de74b3057b074a85fe99fe873b75519bd78.zip

llm -m groq-llama3-70b 'say something exciting about wolves in spanish'
```
Output:

> ¡Los lobos son criaturas majestuosas que nos transportan a un mundo de aventura y misterio! (Wolves are majestic creatures that transport us to a world of adventure and mystery!)
>
> Or, if you'd like a shorter phrase:
>
> ¡Los lobos son los reyes del bosque! (Wolves are the kings of the forest!)
>
> Or, if you want to emphasize their pack behavior:
>
> ¡Los lobos son una familia feroz y leal, luchando juntos por la supervivencia! (Wolves are a fierce and loyal family, fighting together for survival!)

**Comment by rikhuijzer** [comment]
Also works for me with
```
$ llm install git+https://github.com/lexh/llm-groq.git@llama3

$ llm -m groq-llama3-70b 'hi'
Hi! It's nice to meet you. Is there something I can help you with or would you like to chat?
```

**Comment by peterldowns** [comment]
For anyone else waiting on the maintainer here, I manually applied this patch by editing the `llm_groq.py` file in the pipx environment directly:

```shell
$ ls "$(dirname $(readlink -f $(which llm)))"/../lib/python*/site-packages/llm_groq.py
/Users/pd/.local/pipx/venvs/llm/bin/../lib/python3.12/site-packages/llm_groq.py
```

**Comment by angerman** [comment]
Ugh. Sorry folks, I've been traveling.

**Comment by angerman** [comment]
I'm happy to invite @simonw as a co-maintainer to this repository. That should also reduce the bus factor risk (after all it's forkable, but ...)

**Comment by angerman** [comment]
Release should be here now: https://pypi.org/project/llm-groq/0.4/

**Comment by peterldowns** [comment]
Thank you @angerman !

**Pull request merged**
