### PR TITLE
llama-3.3-70b-versatile

### PR DESCRIPTION
**Pull request by simonw**
Refs:
- https://github.com/angerman/llm-groq/issues/9

### CODE REVIEW

**Comment by simonw** [comment]
Tested it like this:
```bash
llm -m groq-llama-3.3-70b 'produce HTML with embedded CSS and JavaScript - no react, no dependencies - for an app that takes a URL to a YouTube video and outputs images along with visible URLs for all known thumbnails for that video'
```
Output here: https://gist.github.com/simonw/8aa22844ace5e0355f1be78dd5c6e067

**Comment by mseri** [comment]
To me it works fine, but the output always terminates with `Error: 'NoneType' object is not iterable`

**Comment by simonw** [comment]
> To me it works fine, but the output always terminates with `Error: 'NoneType' object is not iterable`

That error is causing it not to write to the log - if you run `llm logs -c` after a prompt you won't get the Groq output because it wasn't recorded.

**Comment by angerman** [comment]
Thank you!

**Pull request merged**
